/**
 * A curated set of the most common passwords.
 * Kept in memory as a Set for O(1) lookup.
 * Source: subset of SecLists top-10k passwords.
 */
export const COMMON_PASSWORDS: Set<string> = new Set([
  '123456', 'password', '12345678', 'qwerty', '123456789', '12345', '1234',
  '111111', '1234567', 'dragon', '123123', 'baseball', 'iloveyou', 'monkey',
  'letmein', 'shadow', 'master', '666666', 'qwertyuiop', '123321', 'mustang',
  'michael', '654321', 'superman', '1qaz2wsx', '7777777', 'fuckyou', '121212',
  '000000', 'qazwsx', '123qwe', 'killer', 'trustno1', 'jordan', 'jennifer',
  'zxcvbnm', 'asdfgh', 'hunter', 'buster', 'soccer', 'harley', 'batman',
  'andrew', 'tigger', 'sunshine', 'iloveyou1', 'fuckme', '2000', 'charlie',
  'robert', 'thomas', 'hockey', 'ranger', 'daniel', 'starwars', 'klaster',
  'george', 'computer', 'michelle', 'jessica', 'pepper', '1111', 'zxcvbn',
  '555555', '11111111', '131313', 'freedom', '777777', 'pass', 'maggie',
  '159753', 'aaaaaa', 'ginger', 'princess', 'joshua', 'cheese', 'amanda',
  'summer', 'love', 'ashley', 'nicole', 'chelsea', 'biteme', 'matthew',
  'access', 'yankees', '987654321', 'dallas', 'austin', 'thunder', 'taylor',
  'matrix', 'william', 'corvette', 'hello', 'martin', 'heather', 'secret',
  'fucker', 'merlin', 'diamond', '1234567890', 'hardcore', 'jennifer1',
  'welcome', 'abc123', 'password1', 'password123', 'admin', 'login', 'test',
  'qwerty123', 'pass123', 'pass1234', 'p@ssword', 'p@ss123', 'p@ssw0rd',
  'passw0rd', 'pa$$word', 'pa$$w0rd', 'letmein1', 'changeme', 'changeme1',
  'monkey1', 'dragon1', 'master1', 'shadow1', 'sunshine1', 'princess1',
  'football', 'football1', 'soccer1', 'baseball1', 'basketball', 'hockey1',
  'superman1', 'batman1', 'spiderman', 'spiderman1', 'starwars1', 'pokemon',
  'pokemon1', 'minecraft', 'minecraft1', 'roblox', 'roblox1', 'fortnite',
  'fortnite1', 'gaming', 'gamer', 'hacker', 'hacking', 'hackme', 'root',
  'toor', 'admin123', 'admin1234', 'administrator', 'guest', 'guest123',
  'user', 'user123', 'demo', 'demo123', 'test123', 'test1234', 'testing',
  'sample', 'example', 'default', 'default1', 'temp', 'temp123', 'temporary',
  'abc', 'abcd', 'abcde', 'abcdef', 'abcdefg', 'abcdefgh', 'abcdefghi',
  'qwert', 'qwerty1', 'asdf', 'asdfg', 'asdfgh1', 'zxcv', 'zxcvb',
  '1q2w3e', '1q2w3e4r', '1q2w3e4r5t', 'q1w2e3r4', 'q1w2e3r4t5',
  'asd123', 'qwe123', 'zxc123', '123abc', '321abc', 'abc321',
  'iloveyou2', 'iloveyou3', 'loveyou', 'love123', 'lovely', 'lover',
  'sexy', 'sexy123', 'sex', 'sex123', 'fuck', 'fuck123', 'shit', 'shit123',
  'ass', 'ass123', 'bitch', 'bitch123', 'bastard', 'bastard1',
  'hello123', 'hello1234', 'hi123', 'hey123', 'hey', 'hi',
  'ok', 'ok123', 'yes', 'yes123', 'no', 'no123', 'maybe', 'maybe123',
  'please', 'please1', 'thanks', 'thanks1', 'thank', 'thank1',
  'god', 'god123', 'jesus', 'jesus1', 'christ', 'christ1', 'bible', 'bible1',
  'angel', 'angel1', 'devil', 'devil1', 'satan', 'satan1', 'hell', 'hell1',
  'heaven', 'heaven1', 'life', 'life123', 'live', 'live123', 'death', 'dead',
  'kill', 'kill123', 'murder', 'murder1', 'blood', 'blood1', 'pain', 'pain1',
  'fire', 'fire123', 'water', 'water1', 'earth', 'earth1', 'wind', 'wind1',
  'air', 'air123', 'sky', 'sky123', 'sun', 'sun123', 'moon', 'moon123',
  'star', 'star123', 'stars', 'stars1', 'night', 'night1', 'day', 'day123',
  'time', 'time123', 'money', 'money1', 'cash', 'cash123', 'gold', 'gold1',
  'silver', 'silver1', 'black', 'black1', 'white', 'white1', 'red', 'red123',
  'blue', 'blue123', 'green', 'green1', 'yellow', 'yellow1', 'pink', 'pink1',
  'purple', 'purple1', 'orange', 'orange1', 'brown', 'brown1', 'grey', 'gray',
  'cat', 'cat123', 'dog', 'dog123', 'fish', 'fish123', 'bird', 'bird123',
  'horse', 'horse1', 'tiger', 'tiger1', 'lion', 'lion123', 'bear', 'bear1',
  'wolf', 'wolf123', 'fox', 'fox123', 'rabbit', 'rabbit1', 'snake', 'snake1',
  'eagle', 'eagle1', 'hawk', 'hawk1', 'falcon', 'falcon1', 'raven', 'raven1',
  'phoenix', 'phoenix1', 'dragon123', 'unicorn', 'unicorn1',
  'apple', 'apple1', 'banana', 'banana1', 'cherry', 'cherry1', 'grape',
  'lemon', 'lemon1', 'mango', 'mango1', 'orange1', 'peach', 'peach1',
  'pear', 'pear1', 'plum', 'plum1', 'strawberry', 'strawberry1',
  'house', 'house1', 'home', 'home123', 'car', 'car123', 'truck', 'truck1',
  'bike', 'bike1', 'boat', 'boat1', 'plane', 'plane1', 'train', 'train1',
  'school', 'school1', 'work', 'work123', 'office', 'office1', 'job', 'job1',
  'boss', 'boss1', 'manager', 'manager1', 'staff', 'staff1', 'team', 'team1',
  'group', 'group1', 'club', 'club1', 'party', 'party1', 'fun', 'fun123',
  'game', 'game1', 'play', 'play1', 'sport', 'sport1', 'music', 'music1',
  'movie', 'movie1', 'book', 'book1', 'read', 'read1', 'write', 'write1',
  'code', 'code1', 'hack', 'hack1', 'tech', 'tech1', 'web', 'web123',
  'net', 'net123', 'internet', 'internet1', 'online', 'online1',
  'email', 'email1', 'mail', 'mail1', 'phone', 'phone1', 'mobile', 'mobile1',
  'computer1', 'laptop', 'laptop1', 'desktop', 'desktop1', 'server', 'server1',
  'network', 'network1', 'system', 'system1', 'windows', 'windows1',
  'linux', 'linux1', 'ubuntu', 'ubuntu1', 'mac', 'mac123', 'apple123',
  'google', 'google1', 'facebook', 'facebook1', 'twitter', 'twitter1',
  'instagram', 'instagram1', 'youtube', 'youtube1', 'netflix', 'netflix1',
  'amazon', 'amazon1', 'microsoft', 'microsoft1', 'apple1234',
  'john', 'john1', 'jane', 'jane1', 'james', 'james1', 'jack', 'jack1',
  'jake', 'jake1', 'jason', 'jason1', 'jeff', 'jeff1', 'joe', 'joe123',
  'joey', 'joey1', 'josh', 'josh1', 'justin', 'justin1', 'kevin', 'kevin1',
  'kyle', 'kyle1', 'mark', 'mark1', 'mike', 'mike1', 'nick', 'nick1',
  'paul', 'paul1', 'peter', 'peter1', 'ryan', 'ryan1', 'sam', 'sam123',
  'scott', 'scott1', 'sean', 'sean1', 'steve', 'steve1', 'tim', 'tim123',
  'tom', 'tom123', 'tony', 'tony1', 'tyler', 'tyler1', 'alex', 'alex1',
  'adam', 'adam1', 'alan', 'alan1', 'ben', 'ben123', 'bob', 'bob123',
  'brad', 'brad1', 'brian', 'brian1', 'chris', 'chris1', 'dan', 'dan123',
  'dave', 'dave1', 'david', 'david1', 'eric', 'eric1', 'frank', 'frank1',
  'gary', 'gary1', 'greg', 'greg1', 'henry', 'henry1', 'ian', 'ian123',
  'anna', 'anna1', 'emma', 'emma1', 'lisa', 'lisa1', 'mary', 'mary1',
  'sarah', 'sarah1', 'kate', 'kate1', 'kelly', 'kelly1', 'kim', 'kim123',
  'laura', 'laura1', 'linda', 'linda1', 'lucy', 'lucy1', 'megan', 'megan1',
  'rachel', 'rachel1', 'rebecca', 'rebecca1', 'sandra', 'sandra1',
  'stephanie', 'stephanie1', 'susan', 'susan1', 'victoria', 'victoria1',
  'zoe', 'zoe123', 'alice', 'alice1', 'amy', 'amy123', 'angela', 'angela1',
  'barbara', 'barbara1', 'carol', 'carol1', 'diana', 'diana1', 'donna',
  'donna1', 'elizabeth', 'elizabeth1', 'emily', 'emily1', 'grace', 'grace1',
  'hannah', 'hannah1', 'helen', 'helen1', 'julia', 'julia1', 'karen',
  'karen1', 'katherine', 'katherine1', 'lauren', 'lauren1', 'maria',
  'maria1', 'natalie', 'natalie1', 'olivia', 'olivia1', 'patricia',
  'patricia1', 'samantha', 'samantha1', 'sophia', 'sophia1',
]);
